spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=map_db
    username: sa
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false



server:
  port: 2022


